name: Repolinter

on:
  push:
    branches:
      - main
      
jobs:
  repolinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19.1'
      - name: Install Repolinter
        run: npm install -g repolinter
      - name: Install linguist licensee
        run: npm install -g linguist licensee
      - name: Run Repolinter
        run: repolinter
